apiVersion: apps/v1
kind: Deployment
metadata:
  name: avg-reducer
spec:
  selector:
    matchLabels:
      app: avg-reducer
  template:
    metadata:
      labels:
        app: avg-reducer
    spec:
      containers:
      - name: avg-reducer
        image: georgylevin/avg-reducer
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        env:
        - name: CONFIG_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: pm-config-map
              key: configServerHost
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pm-secret
              key: redisPassword
        - name: CONFLUENT_API_SECRET
          valueFrom:
            secretKeyRef:
              name: pm-secret
              key: confluentIpiSecret